name: Deploy Terraform

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "terraform/**"
  pull_request:
    paths:
    - "terraform/**"
    
jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: terraform
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform apply
      working-directory: terraform
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}