name: Deploy site files

on: 
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "src/**"

jobs:
  upload_files:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: imdevinc-gold-rush
        source_dir: 'src'
        destination_dir: ''