name: Deploy site files

on: 
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "src/**"

jobs:
  upload_files:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Upload files
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: src
        destination: gnomebytes.com
        parent: false